# Generated by Django 5.2.1 on 2025-05-19 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('duration_minutes', models.PositiveIntegerField(editable=False, verbose_name='Duration (minutes)')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is booked')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Available Time',
                'verbose_name_plural': 'Available Times',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.availabletime', verbose_name='Available Time')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.AddConstraint(
            model_name='availabletime',
            constraint=models.UniqueConstraint(fields=('provider', 'start_time'), name='unique_provider_time_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('user', 'available_time')},
        ),
    ]
