# Generated by Django 5.2.1 on 2025-05-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Duration (minutes)'),
        ),
    ]
